# Generated by Django 3.2.13 on 2022-04-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_interviewee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='interviewee',
        ),
    ]
